id_channels: [ly6c, cd3e, cd11c, cd45, cd11b, cd4, ly6g, f480, cd49b, cd8, b220]
other_channels: [fsc, ssc]

random_sample_size: 10000000
random_seed: 2

kernel_low: 1
kernel_high: 99

# fraction of positive value range to jitter channel gates
jitter: 0.05

# optional output path
output_path: '/Users/gjbaker/projects/gbm_immunosuppression'

orthant_dir: os.path.join(project_path, 'postbot', 'data', 'logicle_e20', 'orthant')
aggregate_data_dir: os.path.join(orthant_dir, 'aggregate_datasets')
pickle_dir: os.path.join(orthant_dir, 'pickled_global_vars')
