data_path: /Users/greg/projects/gbm_immunosuppression/cleaned_zeroed_data/combined_csv_file/data.csv
# /Users/greg/projects/sylaras/test_tiny.csv  # 1000 cells
# /Users/greg/projects/gbm_immunosuppression/cleaned_zeroed_data/combined_csv_file/data.csv

id_channels: [ly6c, cd11c, cd3e, cd45, cd11b, cd4, ly6g, f480, cd49b, cd8a, b220]
other_channels: [fsc, ssc]

random_sample_size: 1000000
random_seed: 2

kernel_low: 1
kernel_high: 99
# fraction of positive value range to jitter channel gates
jitter: 0.05
filter_choice: kernel  # choose from full, kernel, and kernel_bias

classes:
  B: [b220, ~cd11b, ~cd11c, ~cd3e, ~cd4, cd45, ~cd49b, ~cd8a, ~f480, ~ly6c, ~ly6g]
  Ly6CposB: [b220, ~cd11b, ~cd11c, ~cd3e, ~cd4, cd45, ~cd49b, ~cd8a, ~f480, ly6c, ~ly6g]
  CD45negB: [b220, ~cd11b, ~cd11c, ~cd3e, ~cd4, ~cd45, ~cd49b, ~cd8a, ~f480, ~ly6c, ~ly6g]
  F480posB: [b220, ~cd11b, ~cd11c, ~cd3e, ~cd4, cd45, ~cd49b, ~cd8a, f480, ~ly6c, ~ly6g]
  CD8aposB: [b220, ~cd11b, ~cd11c, ~cd3e, ~cd4, cd45, ~cd49b, cd8a, ~f480, ~ly6c, ~ly6g]
  CD8T: [~b220, ~cd11b, ~cd11c, cd3e, ~cd4, cd45, ~cd49b, cd8a, ~f480, ~ly6c, ~ly6g]
  Ly6CposCD8T: [~b220, ~cd11b, ~cd11c, cd3e, ~cd4, cd45, ~cd49b, cd8a, ~f480, ly6c, ~ly6g]
  B220posCD8T: [b220, ~cd11b, ~cd11c, cd3e, ~cd4, cd45, ~cd49b, cd8a, ~f480, ~ly6c, ~ly6g]
  CD4T: [~b220, ~cd11b, ~cd11c, cd3e, cd4, cd45, ~cd49b, ~cd8a, ~f480, ~ly6c, ~ly6g]
  Ly6CposCD4T: [~b220, ~cd11b, ~cd11c, cd3e, cd4, cd45, ~cd49b, ~cd8a, ~f480, ly6c, ~ly6g]
  DC: [~b220, cd11b, cd11c, ~cd3e, ~cd4, cd45, ~cd49b, ~cd8a, f480, ly6c, ~ly6g]
  NK: [~b220, cd11b, ~cd11c, ~cd3e, ~cd4, cd45, cd49b, ~cd8a, ~f480, ~ly6c, ~ly6g]
  PMN: [~b220, cd11b, ~cd11c, ~cd3e, ~cd4, cd45, ~cd49b, ~cd8a, ~f480, ly6c, ly6g]
  CD45negPMN: [~b220, cd11b, ~cd11c, ~cd3e, ~cd4, ~cd45, ~cd49b, ~cd8a, ~f480, ly6c, ly6g]
  Ly6CnegPMN: [~b220, cd11b, ~cd11c, ~cd3e, ~cd4, cd45, ~cd49b, ~cd8a, ~f480, ~ly6c, ly6g]
  F480posPMN: [~b220, cd11b, ~cd11c, ~cd3e, ~cd4, cd45, ~cd49b, ~cd8a, f480, ly6c, ly6g]
  F480posLy6CnegPMN: [~b220, cd11b, ~cd11c, ~cd3e, ~cd4, cd45, ~cd49b, ~cd8a, f480, ~ly6c, ly6g]
  Mono: [~b220, cd11b, ~cd11c, ~cd3e, ~cd4, cd45, ~cd49b, ~cd8a, ~f480, ly6c, ~ly6g]
  Ly6CnegMono: [~b220, cd11b, ~cd11c, ~cd3e, ~cd4, cd45, ~cd49b, ~cd8a, ~f480, ~ly6c, ~ly6g]
  CD11bnegMono: [~b220, ~cd11b, ~cd11c, ~cd3e, ~cd4, cd45, ~cd49b, ~cd8a, ~f480, ly6c, ~ly6g]
  Mac: [~b220, cd11b, ~cd11c, ~cd3e, ~cd4, cd45, ~cd49b, ~cd8a, f480, ~ly6c, ~ly6g]
  Ly6CposMac: [~b220, cd11b, ~cd11c, ~cd3e, ~cd4, cd45, ~cd49b, ~cd8a, f480, ly6c, ~ly6g]
  CD11bnegMac: [~b220, ~cd11b, ~cd11c, ~cd3e, ~cd4, cd45, ~cd49b, ~cd8a, f480, ~ly6c, ~ly6g]
  DPT: [~b220, ~cd11b, ~cd11c, ~cd3e, cd4, cd45, ~cd49b, cd8a, ~f480, ~ly6c, ~ly6g]
  CD45negDPT: [~b220, ~cd11b, ~cd11c, ~cd3e, cd4, ~cd45, ~cd49b, cd8a, ~f480, ~ly6c, ~ly6g]
  CD3eposDPT: [~b220, ~cd11b, ~cd11c, cd3e, cd4, cd45, ~cd49b, cd8a, ~f480, ~ly6c, ~ly6g]
  ISPT: [~b220, ~cd11b, ~cd11c, ~cd3e, ~cd4, cd45, ~cd49b, cd8a, ~f480, ~ly6c, ~ly6g]
  CD45negISPT: [~b220, ~cd11b, ~cd11c, ~cd3e, ~cd4, ~cd45, ~cd49b, cd8a, ~f480, ~ly6c, ~ly6g]
  LTi: [~b220, ~cd11b, ~cd11c, ~cd3e, cd4, cd45, ~cd49b, ~cd8a, ~f480, ~ly6c, ~ly6g]
  DNT: [~b220, ~cd11b, ~cd11c, cd3e, ~cd4, cd45, ~cd49b, ~cd8a, ~f480, ~ly6c, ~ly6g]
  Ly6CposDNT: [~b220, ~cd11b, ~cd11c, cd3e, ~cd4, cd45, ~cd49b, ~cd8a, ~f480, ly6c, ~ly6g]
  Precursor: [~b220, ~cd11b, ~cd11c, ~cd3e, ~cd4, cd45, ~cd49b, ~cd8a, ~f480, ~ly6c, ~ly6g]
  CD45negPrecursor: [~b220, ~cd11b, ~cd11c, ~cd3e, ~cd4, ~cd45, ~cd49b, ~cd8a, ~f480, ~ly6c, ~ly6g]

# cutoff for cell states populated by >1% of cells in one or more tissues
alpha: 1.0

# output_path: .
output_path: '/Users/greg/projects/gbm_immunosuppression/postbot/data/logicle_e20/orthant_testing'

# celltypes and markers of interest for scatter plot
celltype1: B
celltype2: CD4T
xaxis_marker: b220
yaxis_marker: cd4
