id_channels: [ly6c, cd3e, cd11c, cd45, cd11b, cd4, ly6g, f480, cd49b, cd8, b220]
other_channels: [fsc, ssc]

random_sample_size: 10000000
random_seed: 2

kernel_low: 1
kernel_high: 99

# fraction of positive value range to jitter channel gates
jitter: 0.05

filter_choice: full

# output_path: .
output_path: '/Users/greg/projects/gbm_immunosuppression/postbot/data/logicle_e20/orthant_testing'
