data_path: '/Users/greg/projects/sylaras/test.csv'

id_channels: [ly6c, cd3e, cd11c, cd45, cd11b, cd4, ly6g, f480, cd49b, cd8, b220]
other_channels: [fsc, ssc]

random_sample_size: 10000000
random_seed: 2

kernel_low: 1
kernel_high: 99

# fraction of positive value range to jitter channel gates
jitter: 0.05

filter_choice: full

classes:
  B: [~CD3e, ~CD49b, B220, ~CD11c, CD45, ~Ly6C, ~Ly6G, ~CD11b, ~CD4, ~CD8a, ~F480]
  Ly6CposB: [~CD3e, ~CD49b, B220, ~CD11c, Ly6C, CD45, ~Ly6G, ~CD11b, ~CD4, ~CD8a, ~F480]
  CD45negB: [~CD3e, ~CD49b, B220, ~CD11c, ~Ly6C, ~Ly6G, ~CD11b, ~CD4, ~CD45, ~CD8a, ~F480]
  F480posB: [~CD3e, ~CD49b, B220, ~CD11c, CD45, ~Ly6C, F480, ~Ly6G, ~CD11b, ~CD4, ~CD8a]
  CD8aposB: [~CD3e, ~CD49b, B220, ~CD11c, CD45, ~Ly6C, ~Ly6G, ~CD11b, ~CD4, ~F480, CD8a]
  CD8T: [~CD49b, ~CD11c, ~B220, CD3e, CD45, ~Ly6C, ~Ly6G, ~CD11b, ~CD4, ~F480, CD8a]
  Ly6CposCD8T: [~CD49b, ~CD11c, ~B220, CD3e, CD45, Ly6C, ~Ly6G, ~CD11b, ~CD4, ~F480, CD8a]
  B220posCD8T: [~CD49b, B220, ~CD11c, CD3e, CD45, ~Ly6C, ~Ly6G, ~CD11b, ~CD4, ~F480, CD8a]
  CD4T: [~CD49b, ~CD11c, ~B220, CD3e, CD4, CD45, ~Ly6C, ~Ly6G, ~CD11b, ~CD8a, ~F480]
  Ly6CposCD4T: [~CD49b, ~CD11c, ~B220, CD3e, CD4, CD45, Ly6C, ~Ly6G, ~CD11b, ~CD8a, ~F480]
  DC: [~CD3e, ~CD49b, ~B220, CD45, Ly6C, F480, ~Ly6G, CD11b, ~CD4, ~CD8a, CD11c]
  NK: [~CD3e, ~CD11c, ~B220, CD45, ~Ly6C, CD49b, ~Ly6G, CD11b, ~CD4, ~CD8a, ~F480]
  PMN: [Ly6G, ~CD3e, ~CD49b, ~CD11c, ~B220, CD45, Ly6C, CD11b, ~CD4, ~CD8a, ~F480]
  CD45negPMN: [Ly6G, ~CD3e, ~CD49b, ~CD11c, ~B220, Ly6C, CD11b, ~CD4, ~CD45, ~CD8a, ~F480]
  Ly6CnegPMN: [Ly6G, ~CD3e, ~CD49b, ~CD11c, ~B220, CD45, ~Ly6C, CD11b, ~CD4, ~CD8a, ~F480]
  F480posPMN: [Ly6G, ~CD3e, ~CD49b, ~CD11c, ~B220, CD45, Ly6C, F480, CD11b, ~CD4, ~CD8a]
  F480posLy6CnegPMN: [Ly6G, ~CD3e, ~CD49b, ~CD11c, ~B220, CD45, ~Ly6C, F480, CD11b, ~CD4, ~CD8a]
  Mono: [~CD3e, ~CD49b, ~CD11c, ~B220, CD45, Ly6C, ~Ly6G, CD11b, ~CD4, ~CD8a, ~F480]
  Ly6CnegMono: [~CD3e, ~CD49b, ~CD11c, ~B220, CD45, ~Ly6C, ~Ly6G, CD11b, ~CD4, ~CD8a, ~F480]
  CD11bnegMono: [~CD3e, ~CD49b, ~CD11c, ~B220, CD45, Ly6C, ~Ly6G, ~CD11b, ~CD4, ~CD8a, ~F480]
  Mac: [~CD3e, ~CD49b, ~CD11c, ~B220, CD45, ~Ly6C, F480, ~Ly6G, CD11b, ~CD4, ~CD8a]
  Ly6CposMac: [~CD3e, ~CD49b, ~CD11c, ~B220, CD45, Ly6C, F480, ~Ly6G, CD11b, ~CD4, ~CD8a]
  CD11bnegMac: [~CD3e, ~CD49b, ~CD11c, ~B220, CD45, ~Ly6C, F480, ~Ly6G, ~CD11b, ~CD4, ~CD8a]
  DPT: [~CD3e, ~CD49b, ~CD11c, ~B220, CD45, CD4, ~Ly6C, ~Ly6G, ~CD11b, ~F480, CD8a]
  CD45negDPT: [~CD3e, ~CD49b, ~CD11c, ~B220, ~Ly6C, CD4, ~Ly6G, ~CD11b, ~CD45, ~F480, CD8a]
  CD3eposDPT: [~CD49b, ~CD11c, ~B220, CD3e, CD4, CD45, ~Ly6C, ~Ly6G, ~CD11b, ~F480, CD8a]
  ISPT: [~CD3e, ~CD49b, ~CD11c, ~B220, CD45, ~Ly6C, ~Ly6G, ~CD11b, ~CD4, ~F480, CD8a]
  CD45negISPT: [~CD3e, ~CD49b, ~CD11c, ~B220, ~Ly6C, ~Ly6G, ~CD11b, ~CD4, ~CD45, ~F480, CD8a]
  LTi: [~CD3e, ~CD49b, ~CD11c, ~B220, CD45, CD4, ~Ly6C, ~Ly6G, ~CD11b, ~CD8a, ~F480]
  DNT: [~CD49b, ~CD11c, ~B220, CD3e, CD45, ~Ly6C, ~Ly6G, ~CD11b, ~CD4, ~CD8a, ~F480]
  Ly6CposDNT: [~CD49b, ~CD11c, ~B220, CD3e, CD45, Ly6C, ~Ly6G, ~CD11b, ~CD4, ~CD8a, ~F480]
  Precursor: [~CD3e, ~CD49b, ~CD11c, ~B220, CD45, ~Ly6C, ~Ly6G, ~CD11b, ~CD4, ~CD8a, ~F480]
  CD45negPrecursor: [~CD3e, ~CD49b, ~CD11c, ~B220, ~Ly6C, ~Ly6G, ~CD11b, ~CD4, ~CD45, ~CD8a, ~F480]


# output_path: .
output_path: '/Users/greg/projects/gbm_immunosuppression/postbot/data/logicle_e20/orthant_testing'
