data_path: /Users/greg/projects/sylaras/input/sylaras_input.parquet

id_channels: [b220, cd11b, cd11c, cd3e, cd4, cd45, cd49b, cd8a, f480, ly6c, ly6g]
other_channels: [fsc, ssc]

random_sample_size: 1000000
random_seed: 2

kernel_low: 1
kernel_high: 99

# fraction of positive value range to jitter channel gates
jitter: 0.05
filter_choice: kernel  # choose from full, kernel, and kernel_bias

# specify Boolean immunophenotype signature and class membership
classes:
  B: [[b220, ~cd11b, ~cd11c, ~cd3e, ~cd4, cd45, ~cd49b, ~cd8a, ~f480, ~ly6c, ~ly6g], lymphoid, landmark population]
  Ly6CposB: [[b220, ~cd11b, ~cd11c, ~cd3e, ~cd4, cd45, ~cd49b, ~cd8a, ~f480, ly6c, ~ly6g], lymphoid]
  CD45negB: [[b220, ~cd11b, ~cd11c, ~cd3e, ~cd4, ~cd45, ~cd49b, ~cd8a, ~f480, ~ly6c, ~ly6g], lymphoid]
  F480posB: [[b220, ~cd11b, ~cd11c, ~cd3e, ~cd4, cd45, ~cd49b, ~cd8a, f480, ~ly6c, ~ly6g], lymphoid]
  CD8aposB: [[b220, ~cd11b, ~cd11c, ~cd3e, ~cd4, cd45, ~cd49b, cd8a, ~f480, ~ly6c, ~ly6g], lymphoid]
  CD8T: [[~b220, ~cd11b, ~cd11c, cd3e, ~cd4, cd45, ~cd49b, cd8a, ~f480, ~ly6c, ~ly6g], lymphoid, landmark population]
  Ly6CposCD8T: [[~b220, ~cd11b, ~cd11c, cd3e, ~cd4, cd45, ~cd49b, cd8a, ~f480, ly6c, ~ly6g], lymphoid]
  B220posCD8T: [[b220, ~cd11b, ~cd11c, cd3e, ~cd4, cd45, ~cd49b, cd8a, ~f480, ~ly6c, ~ly6g], lymphoid]
  CD4T: [[~b220, ~cd11b, ~cd11c, cd3e, cd4, cd45, ~cd49b, ~cd8a, ~f480, ~ly6c, ~ly6g], lymphoid, landmark population]
  Ly6CposCD4T: [[~b220, ~cd11b, ~cd11c, cd3e, cd4, cd45, ~cd49b, ~cd8a, ~f480, ly6c, ~ly6g], lymphoid]
  DC: [[~b220, cd11b, cd11c, ~cd3e, ~cd4, cd45, ~cd49b, ~cd8a, f480, ly6c, ~ly6g], myeloid, landmark population]
  NK: [[~b220, cd11b, ~cd11c, ~cd3e, ~cd4, cd45, cd49b, ~cd8a, ~f480, ~ly6c, ~ly6g], lymphoid, landmark population]
  PMN: [[~b220, cd11b, ~cd11c, ~cd3e, ~cd4, cd45, ~cd49b, ~cd8a, ~f480, ly6c, ly6g], myeloid, landmark population]
  CD45negPMN: [[~b220, cd11b, ~cd11c, ~cd3e, ~cd4, ~cd45, ~cd49b, ~cd8a, ~f480, ly6c, ly6g], myeloid]
  Ly6CnegPMN: [[~b220, cd11b, ~cd11c, ~cd3e, ~cd4, cd45, ~cd49b, ~cd8a, ~f480, ~ly6c, ly6g], myeloid]
  F480posPMN: [[~b220, cd11b, ~cd11c, ~cd3e, ~cd4, cd45, ~cd49b, ~cd8a, f480, ly6c, ly6g], myeloid]
  F480posLy6CnegPMN: [[~b220, cd11b, ~cd11c, ~cd3e, ~cd4, cd45, ~cd49b, ~cd8a, f480, ~ly6c, ly6g], myeloid]
  Mono: [[~b220, cd11b, ~cd11c, ~cd3e, ~cd4, cd45, ~cd49b, ~cd8a, ~f480, ly6c, ~ly6g], myeloid, landmark population]
  Ly6CnegMono: [[~b220, cd11b, ~cd11c, ~cd3e, ~cd4, cd45, ~cd49b, ~cd8a, ~f480, ~ly6c, ~ly6g], myeloid]
  CD11bnegMono: [[~b220, ~cd11b, ~cd11c, ~cd3e, ~cd4, cd45, ~cd49b, ~cd8a, ~f480, ly6c, ~ly6g], myeloid]
  Mac: [[~b220, cd11b, ~cd11c, ~cd3e, ~cd4, cd45, ~cd49b, ~cd8a, f480, ~ly6c, ~ly6g], myeloid, landmark population]
  Ly6CposMac: [[~b220, cd11b, ~cd11c, ~cd3e, ~cd4, cd45, ~cd49b, ~cd8a, f480, ly6c, ~ly6g], myeloid]
  CD11bnegMac: [[~b220, ~cd11b, ~cd11c, ~cd3e, ~cd4, cd45, ~cd49b, ~cd8a, f480, ~ly6c, ~ly6g], myeloid]
  DPT: [[~b220, ~cd11b, ~cd11c, ~cd3e, cd4, cd45, ~cd49b, cd8a, ~f480, ~ly6c, ~ly6g], lymphoid, landmark population]
  CD45negDPT: [[~b220, ~cd11b, ~cd11c, ~cd3e, cd4, ~cd45, ~cd49b, cd8a, ~f480, ~ly6c, ~ly6g], lymphoid]
  CD3eposDPT: [[~b220, ~cd11b, ~cd11c, cd3e, cd4, cd45, ~cd49b, cd8a, ~f480, ~ly6c, ~ly6g], lymphoid]
  ISPT: [[~b220, ~cd11b, ~cd11c, ~cd3e, ~cd4, cd45, ~cd49b, cd8a, ~f480, ~ly6c, ~ly6g], lymphoid]
  CD45negISPT: [[~b220, ~cd11b, ~cd11c, ~cd3e, ~cd4, ~cd45, ~cd49b, cd8a, ~f480, ~ly6c, ~ly6g], lymphoid]
  LTi: [[~b220, ~cd11b, ~cd11c, ~cd3e, cd4, cd45, ~cd49b, ~cd8a, ~f480, ~ly6c, ~ly6g], lymphoid]
  DNT: [[~b220, ~cd11b, ~cd11c, cd3e, ~cd4, cd45, ~cd49b, ~cd8a, ~f480, ~ly6c, ~ly6g], lymphoid, landmark population]
  Ly6CposDNT: [[~b220, ~cd11b, ~cd11c, cd3e, ~cd4, cd45, ~cd49b, ~cd8a, ~f480, ly6c, ~ly6g], lymphoid]
  Precursor: [[~b220, ~cd11b, ~cd11c, ~cd3e, ~cd4, cd45, ~cd49b, ~cd8a, ~f480, ~ly6c, ~ly6g], other, landmark population]
  CD45negPrecursor: [[~b220, ~cd11b, ~cd11c, ~cd3e, ~cd4, ~cd45, ~cd49b, ~cd8a, ~f480, ~ly6c, ~ly6g], other]

# cutoff for cell states populated by >1% of cells in one or more tissues
alpha: 1.0

# output_path
output_path: /Users/greg/projects/sylaras/output

# celltypes and markers of interest for scatter plot
celltype1: B
celltype2: CD4T
xaxis_marker: b220
yaxis_marker: cd4
